### ISSUE TITLE
converge panics when interrupted

### ISSUE THREAD

**Issue by ryane** [asteris-llc/converge#318]
converge currently panics when interrupting a run:

``` shell
$ ./converge plan --local samples/shellExit.hcl
2016-09-28T10:58:17-04:00 |INFO| serving        addr=:47740 component=rpc
2016-09-28T10:58:17-04:00 |WARN| skipping module verification   component=client
2016-09-28T10:58:17-04:00 |INFO| got status     component=client file=samples/shellExit.hcl id=root/task.slow run=STARTED stage=PLAN
^C2016-09-28T10:58:18-04:00 |INFO| gracefully shutting down (interrupt again to halt)
2016-09-28T10:58:18-04:00 |FATAL| failed to serve       addr=:47740 component=rpc error=accept tcp [::]:47740: use of closed network connection
panic: Unexpected error from context packet: context canceled

goroutine 25 [running]:
panic(0x5c8fa0, 0xc420016f40)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/asteris-llc/converge/vendor/google.golang.org/grpc/transport.ContextErr(0x9bd2c0, 0xc4200781a0, 0xc4200781a0, 0x1, 0x0)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/vendor/google.golang.org/grpc/transport/transport.go:549 +0x213
github.com/asteris-llc/converge/vendor/google.golang.org/grpc.NewClientStream.func2(0x9c9b40, 0xc42006f000, 0xc4200e60f0, 0xc4200a7b00)
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/vendor/google.golang.org/grpc/stream.go:215 +0x3a0
created by github.com/asteris-llc/converge/vendor/google.golang.org/grpc.NewClientStream
        /Users/ryan/Projects/golang/src/github.com/asteris-llc/converge/vendor/google.golang.org/grpc/stream.go:217 +0xb83
```

**Comment by BrianHicks** [comment]
That's actually not a panic. When we use `errors.Wrap` it attaches a stacktrace to the error. When the error is printed with "%v" it prints that out as well.

That said, the custom logger (which it looks like you're using) purposely uses "%s" to avoid this problem. Some other component may be `fmt.Errorf`ing the error and printing that trace.

**Comment by ryane** [comment]
it looks like this is due to the fact that we are using the 1.7 "context" package in our cmds but the grpc-go library still uses "golang.org/x/net/context" [1]. The switch at https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L560 will not correctly match the `context.Canceled` err and panic. If I rebuild using "golang.org/x/net/context", converge is able to stop more gracefully:

```
./converge apply --local samples/wait.hcl
2016-10-25T16:27:09-04:00 |INFO| serving        addr=:47740 component=rpc
2016-10-25T16:27:09-04:00 |WARN| skipping module verification   component=client
2016-10-25T16:27:09-04:00 |INFO| resolving conditional macros   component=rpc function=ResolveConditionals runID=029fa101-c834-431c-9ba0-c6d3a9fdcc25
2016-10-25T16:27:09-04:00 |INFO| got status     component=client file=samples/wait.hcl id=root/wait.query.service-health run=STARTED stage=APPLY
^C2016-10-25T16:27:11-04:00 |INFO| gracefully shutting down (interrupt again to halt)
2016-10-25T16:27:11-04:00 |FATAL| could not get responses       component=client error=error getting status response: rpc error: code = 1 desc = context canceled file=samples/wait.hcl
```

Should we just use "golang.org/x/net/context" until the dependency is updated? Other ideas?

[1] https://github.com/grpc/grpc-go/issues/711

**Comment by stevendborrelli** [comment]
@ryane I'm with you on using x/net/context.
